name: Flutter Build (Unity 6)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Для Unity 6 обязательно нужен JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. Установка NDK r27c (требование Unity 6 для Android)
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
          add-to-path: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: example

      - name: Build APK
        run: |
          # Указываем путь к NDK вручную, чтобы Gradle его точно увидел
          flutter build apk --release --target-platform android-arm64
        working-directory: example
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: example/build/app/outputs/flutter-apk/app-release.apk