name: Flutter Build

on:
  push:
    branches: [ "master" ] # Проверьте, что у вас master, а не main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Установка NDK (необходим для Unity-библиотек)
      - name: Install Android NDK
        uses: nnbnh/setup-ndk@v1
        with:
          ndk-version: r23c # Стабильная версия для большинства Unity-проектов

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: example

      - name: Build APK
        # Собираем только arm64, чтобы сэкономить время и память в облаке
        run: flutter build apk --release --target-platform android-arm64
        working-directory: example

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: example/build/app/outputs/flutter-apk/app-release.apk